### PR TITLE
Tech Onboarding docs for major OSs

### PR DESCRIPTION
**Pull request by danielrazavi**
Created markdown files that learners can follow along to install the necessary tools on their personal computers.

### CODE REVIEW

**Comment by kaylielau** [comment]
Can we include plotly and kaleido in the installation?

**Comment by danielrazavi** [comment]
> Can we include plotly and kaleido in the installation?

yes of course, I have created a new revision of the PR that it addresses that.

**Comment by dtxe** [comment]
Looks good on my end.

**Comment by kaylielau** [comment]
Good on my end as well!

**Comment by danielrazavi** [comment]
Reviewed by Instructors and Approved.

**Pull request merged**
