### PR TITLE
new scripts made in order to aid learners.

### PR DESCRIPTION
**Pull request by danielrazavi**
New scripts have been created to facilitate git setup for learners in the Unix shell repository. These scripts also aid learners in practicing the execution of commands in a bash environment. Additionally, they help users become more comfortable with executing git commands and using version control services.

### CODE REVIEW

**Review by RohanAlexander — APPROVED** [review]
I tried this on a Mac, and it all seemed to work (I had issues with moving the file, but that's probably a me problem). I think this should be given to the instructors of the intro to Unix Shell, Git and GitHub for comments about what needs to be updated to fit their needs. 

Bigger picture - we should think about whether this is best hosted in this repo, or in the intro to unix shell, git and GitHub repo.

Anyway, this is a nice idea, and once we're sure it works on real students will be a nice time saver.

**Comment by dtxe** [comment]
I'm getting this error in both Command Prompt and Powershell 7 (we should probably focus on Powershell).

Suggestion for the Windows setup script: try automatically installing Git using winget.
`winget install --id Git.Git -e --source winget --disable-interactivity`

image

**Comment by dtxe** [comment]
Suggestion for the Windows setup script: try automatically installing Git using winget.
`winget install --id Git.Git -e --source winget --disable-interactivity`

**Comment by dtxe** [comment]
Everything works great in Git Bash for Windows (git version 2.43.0.windows.1)

Some minor issues:
- The script will run in a non-empty directory and doesn't currently check if the mkdir instructions were followed. This means it might be used in a directory with potentially private stuff files being committed to the repo. Suggestion: add a step to make an empty directory within the tutorial proper, before `git init` OR check that the current directory is empty except for the current script.
- When capturing commands, experienced learners may try to use the arrow keys, which register as characters and will cause any entered commands to show as incorrect. Consider stripping non-printing or non-alphanumeric-symbol characters from commands when running/validating.

**Pull request closed without merging**
